(cd html/experts/general     && bash install_libs.bash && php ../../../tools/composer/composer.phar install)
(cd html/experts/illustrator && bash install_libs.bash && php ../../../tools/composer/composer.phar install)
(cd html/experts/remote_llms && bash install_libs.bash && php ../../../tools/composer/composer.phar install)
(cd html/experts/classifier && bash install_libs.bash && php ../../../tools/composer/composer.phar install)
(cd html/experts/humorist && bash install_libs.bash && php ../../../tools/composer/composer.phar install)
(cd html/experts/robotics && bash install_libs.bash && php ../../../tools/composer/composer.phar install)

(cd html/units/github_login     && bash install_libs.bash && php ../../../tools/composer/composer.phar install)
(cd html/units/google_login && bash install_libs.bash && php ../../../tools/composer/composer.phar install)
(cd html/units/hcaptcha && bash install_libs.bash && php ../../../tools/composer/composer.phar install)
(cd html/units/logout && bash install_libs.bash && php ../../../tools/composer/composer.phar install)
(cd html/units/settings && bash install_libs.bash && php ../../../tools/composer/composer.phar install)
