(cd html/experts/general     && bash install_libs.bash)
(cd html/experts/illustrator && bash install_libs.bash)
(cd html/experts/remote_llms && bash install_libs.bash)
(cd html/experts/classifier && bash install_libs.bash)
(cd html/experts/humorist && bash install_libs.bash)
(cd html/experts/robotics && bash install_libs.bash)
